### ISSUE TITLE
AX86U support

### ISSUE THREAD

**Issue by de-vnull** [Adamm00/ChannelHog#2]
Another user identified and fixed the issue: https://www.snbforums.com/threads/channelhog-monitor-and-force-maximum-5ghz-bandwidth-for-ax88u.61131/post-689735

**Comment by Adamm00** [comment]
Fixed in 029840a6d76919cfa517fbebd42670e8664fc7f0


fwiw: I am still very busy, my free time is virtually non existent. I respond to all GitHub issues when I can and if they are legitimate bugs.
